version: "3.8"

services:
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
  mysql:
    container_name: mysql
    image: mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mntVolumeMYSQL:/var/lib/mysql
      

